#!/usr/bin/env bash

OPENCV_URL="https://github.com/Itseez/opencv.git"
OPENCV_PACKAGE_NAME="opencv"
OPENCV_CONTRIB_URL="https://github.com/Itseez/opencv_contrib.git"
OPENCV_CONTRIB_PACKAGE_NAME="opencv_contrib"

PREFIX="${PREFIX:-/usr/local}"

install_build_dependencies() {
    sudo apt-get install -y build-essential cmake git pkg-config 
	sudo apt-get install -y libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev  libavcodec-dev libavformat-dev libswscale-dev
    sudo apt-get install -y libgtk2.0-dev
    sudo apt-get install -y python-dev python-numpy  python2.7-dev python3-dev 
}


download_packages() {
    git clone "$OPENCV_URL"
    git clone "$OPENCV_CONTRIB_URL"
}


build() {
    cmake -D CMAKE_BUILD_TYPE=RELEASE \
          -D CMAKE_INSTALL_PREFIX="$PREFIX" \
          -D INSTALL_C_EXMAPLES=ON \
          -D INSTALL_PYTHON_EXAMPLES=ON \
          -D OPENCV_EXTRA_MODULES_PATH="$HOME/$OPENCV_CONTRIB_PACKAGE_NAME/modules" \
          -D BUILD_EXAMPLES=ON\
          ..
    make -j4
}

install() {
    sudo make install
}

log() {
    local msg="$1"; shift
    local _color_bold_yellow='\e[1;33m'
    local _color_reset='\e[0m'
    echo -e "\[${_color_bold_yellow}\]${msg}\[${_color_reset}\]"
}

main() {
    log "Instalacja pakietow..."
    install_build_dependencies
    log "Pobieranie OpenCV..."
    download_packages
    log "Building OpenCV..."
    cd "$OPENCV_PACKAGE_NAME"
    mkdir build
    cd build
    build
    echo "Installing OpenCV..."
    install
	echo "Zainstalowano pomyślnie"
}

main

